name: "Open-AI Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI API."
inputs:
  name:
    description: 'The name of the person to greet'
    required: true
    default: 'World'
 
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"